# -*- coding: utf-8 -*-
"""QFC Momentum Code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlY9oBFhclA36Ca1Wp19lfDX29-SCKbc
"""

import yfinance as yf
import pandas as pd
import matplotlib.pyplot as plt
import requests

url = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)
sp500 = pd.read_html(response.text)[0]
sp500["Symbol"] = sp500["Symbol"].str.replace(".", "-", regex=False)
sectors = ["Information Technology", "Industrials", "Consumer Discretionary"]
sp500 = sp500[sp500["GICS Sector"].isin(sectors)]
tickers = sp500["Symbol"].tolist()
prices = yf.download(tickers, start="2026-01-01")["Close"]
momentum = prices.pct_change(20).iloc[-1].dropna()
top_n = 5

for sector in sectors:
    sector_tickers = sp500[sp500["GICS Sector"] == sector]["Symbol"]
    sector_momentum = momentum[sector_tickers].dropna()
    top_stocks = sector_momentum.sort_values(ascending=False).head(top_n).index.tolist()

    print("\n", sector)
    print(top_stocks)
    sector_prices = prices[top_stocks]
    returns = sector_prices.pct_change().dropna()
    portfolio_returns = returns.mean(axis=1)
    portfolio_growth = (1 + portfolio_returns).cumprod()
    print("Final Portfolio Value:", portfolio_growth.iloc[-1])

    plt.figure(figsize=(10,6))
    plt.plot(portfolio_growth)
    plt.title(f"{sector} Momentum Portfolio")
    plt.xlabel("Date")
    plt.ylabel("Growth of $1")
    plt.show()

for sector in sectors:
    stocks = sp500[sp500["GICS Sector"] == sector]["Symbol"]
    sector_momentum = momentum[stocks]
    top_stocks = sector_momentum.sort_values(ascending=False).head(3).index
    data = prices[top_stocks]
    returns = data.pct_change().dropna()
    (1 + returns).cumprod().plot(title=sector)
    plt.show()

for sector in sectors:
    stocks = sp500[sp500["GICS Sector"] == sector]["Symbol"]
    sector_momentum = momentum[stocks]
    top_stocks = sector_momentum.sort_values(ascending=False).head(3).index
    data = prices[top_stocks]
    returns = data.pct_change().dropna()
    weights = [0.5, 0.3, 0.2]
    portfolio_returns = returns.dot(weights)
    portfolio_growth = (1 + portfolio_returns).cumprod()
    print("\n", sector)
    print("Top Stocks:", top_stocks.tolist())
    print("Final Portfolio Value:", portfolio_growth.iloc[-1])
    portfolio_growth.plot(title=sector + " Portfolio")
    plt.show()

yield_percent = 3.6
rf = yield_percent / 100
rf

"""Change cell below to "Information Technology" / "Industrials" / "Consumer Discretionary" THEN run the cells below"""

sector = "Industrials"

stocks = sp500[sp500["GICS Sector"] == sector]["Symbol"]
sector_momentum = momentum[stocks].dropna()
top_stocks = sector_momentum.sort_values(ascending=False).head(3).index
top_stocks

data = prices[top_stocks]
returns = data.pct_change().dropna()
returns.tail()

returns.corr()

volatility = returns.std() * (252 ** 0.5)
volatility.name = "Volatility"
volatility

growth = (1 + returns).cumprod()
drawdown = growth / growth.cummax() - 1
max_drawdown = drawdown.min()
max_drawdown.name = "Max Drawdown"
max_drawdown

sharpe = ((returns.mean() * 252) - rf) / volatility
sharpe.name = "Sharpe"
sharpe